
#include "motor.h"


static void MOTOR_SET_SPEED(u8 speed);
/////////////////////////////////////H-bridge pins initialization///////////////////////////////////////////////////////////

GPIO_configurationsType input1PinBack  =  {H_BRIDGE_INPUT1_PORT,H_BRIDGE_INPUT1_PIN,GPIO_OUTPUT_PUSH_PULL_MODE,GPIO_MEDIUM_SPEED};
GPIO_configurationsType input1PinFront = {H_BRIDGE_INPUT1_PORT,H_BRIDGE_INPUT2_PIN,GPIO_OUTPUT_PUSH_PULL_MODE,GPIO_MEDIUM_SPEED};






GPIO_configurationsType input2PinBack  = {H_BRIDGE_INPUT2_PORT,H_BRIDGE_INPUT3_PIN,GPIO_OUTPUT_PUSH_PULL_MODE,GPIO_MEDIUM_SPEED};
GPIO_configurationsType input2PinFront = {H_BRIDGE_INPUT2_PORT,H_BRIDGE_INPUT4_PIN,GPIO_OUTPUT_PUSH_PULL_MODE,GPIO_MEDIUM_SPEED};


DcMotor_State state;
/*
initialize DCmotor by passing channel and timer IDs to the PWM init
*/
void DCmotor_Init(void)
{
	GPIO_configurePin(&input1PinBack);
	GPIO_configurePin(&input2PinBack);
	GPIO_configurePin(&input1PinFront);
	GPIO_configurePin(&input2PinFront);
	GPIO_writePin(H_BRIDGE_INPUT1_PORT,H_BRIDGE_INPUT1_PIN,GPIO_LOW_PIN);
	GPIO_writePin(H_BRIDGE_INPUT2_PORT,H_BRIDGE_INPUT4_PIN,GPIO_LOW_PIN);
	GPIO_writePin(H_BRIDGE_INPUT1_PORT,H_BRIDGE_INPUT2_PIN,GPIO_LOW_PIN);
	GPIO_writePin(H_BRIDGE_INPUT2_PORT,H_BRIDGE_INPUT3_PIN,GPIO_LOW_PIN);
	PWM_enu_Init(DCMOTOR_SELECT_TIMER,DCMOTOR_SELECT_CHANNEL1);
	PWM_enu_Init(DCMOTOR_SELECT_TIMER2,DCMOTOR_SELECT_CHANNEL1);
}

void DCmotor_frontMove(u8 dutyCycle)
{
	
	GPIO_writePin(H_BRIDGE_INPUT1_PORT,H_BRIDGE_INPUT3_PIN,GPIO_HIGH_PIN);
	GPIO_writePin(H_BRIDGE_INPUT1_PORT,H_BRIDGE_INPUT1_PIN,GPIO_HIGH_PIN);

	MOTOR_SET_SPEED(dutyCycle);
	/*ganb ymen wra*/
	GPIO_writePin(H_BRIDGE_INPUT2_PORT,H_BRIDGE_INPUT2_PIN,GPIO_LOW_PIN);
	GPIO_writePin(H_BRIDGE_INPUT2_PORT,H_BRIDGE_INPUT4_PIN,GPIO_LOW_PIN);
	

	
}
void DCmotor_backMove(u8 dutyCycle)
{
	
	MOTOR_SET_SPEED(dutyCycle);
		/*ganb shmal odam*/
	GPIO_writePin(H_BRIDGE_INPUT2_PORT,H_BRIDGE_INPUT2_PIN,GPIO_HIGH_PIN);
	GPIO_writePin(H_BRIDGE_INPUT2_PORT,H_BRIDGE_INPUT4_PIN,GPIO_HIGH_PIN);

	/*ganb ymen odam*/
	GPIO_writePin(H_BRIDGE_INPUT1_PORT,H_BRIDGE_INPUT1_PIN,GPIO_LOW_PIN);
	GPIO_writePin(H_BRIDGE_INPUT1_PORT,H_BRIDGE_INPUT3_PIN,GPIO_LOW_PIN);


	
}

// input1 right motors , input2 left motors
void DCmotor_rightMove(u8 dutyCycle)
{
	MOTOR_SET_SPEED(dutyCycle);
	GPIO_writePin(H_BRIDGE_INPUT2_PORT,H_BRIDGE_INPUT4_PIN,GPIO_LOW_PIN);
	GPIO_writePin(H_BRIDGE_INPUT1_PORT,H_BRIDGE_INPUT1_PIN,GPIO_LOW_PIN);
	
	GPIO_writePin(H_BRIDGE_INPUT2_PORT,H_BRIDGE_INPUT2_PIN,GPIO_HIGH_PIN);
	GPIO_writePin(H_BRIDGE_INPUT1_PORT,H_BRIDGE_INPUT3_PIN,GPIO_HIGH_PIN);

	
}
void DCmotor_leftMove(u8 dutyCycle)
{
	MOTOR_SET_SPEED(dutyCycle);
	GPIO_writePin(H_BRIDGE_INPUT2_PORT,H_BRIDGE_INPUT2_PIN,GPIO_LOW_PIN);
	GPIO_writePin(H_BRIDGE_INPUT1_PORT,H_BRIDGE_INPUT3_PIN,GPIO_LOW_PIN);
	
	GPIO_writePin(H_BRIDGE_INPUT2_PORT,H_BRIDGE_INPUT4_PIN,GPIO_HIGH_PIN);
	GPIO_writePin(H_BRIDGE_INPUT1_PORT,H_BRIDGE_INPUT1_PIN,GPIO_HIGH_PIN);

	
}
/*
stop the DCmotor by passing dutycycle = 0
*/
void DCmotor_stop(void)
{
	MOTOR_SET_SPEED(FALSE);
	GPIO_writePin(H_BRIDGE_INPUT1_PORT,H_BRIDGE_INPUT1_PIN,GPIO_LOW_PIN);
	GPIO_writePin(H_BRIDGE_INPUT2_PORT,H_BRIDGE_INPUT4_PIN,GPIO_LOW_PIN);
	GPIO_writePin(H_BRIDGE_INPUT1_PORT,H_BRIDGE_INPUT2_PIN,GPIO_LOW_PIN);
	GPIO_writePin(H_BRIDGE_INPUT2_PORT,H_BRIDGE_INPUT3_PIN,GPIO_LOW_PIN);
	
}


/*FOR TESTING ONLY*/
void DCmotor1_(void)
{
	/*ganb ymen wra*/
	GPIO_writePin(H_BRIDGE_INPUT1_PORT,H_BRIDGE_INPUT1_PIN,GPIO_LOW_PIN);
	GPIO_writePin(H_BRIDGE_INPUT2_PORT,H_BRIDGE_INPUT2_PIN,GPIO_HIGH_PIN);
}

void DCmotor2_(void)
{
		/*ganb PPPPPPPP shmal odam*/

	GPIO_writePin(H_BRIDGE_INPUT1_PORT,H_BRIDGE_INPUT3_PIN,GPIO_LOW_PIN);
	GPIO_writePin(H_BRIDGE_INPUT2_PORT,H_BRIDGE_INPUT4_PIN,GPIO_HIGH_PIN);
}
void DCmotor3_(void)
{
		/*ganb shmal odam*/

	GPIO_writePin(H_BRIDGE_INPUT1_PORT,H_BRIDGE_INPUT3_PIN,GPIO_HIGH_PIN);
	GPIO_writePin(H_BRIDGE_INPUT2_PORT,H_BRIDGE_INPUT4_PIN,GPIO_LOW_PIN);
}

void DCmotor4_(void)
{
			/*ganb ymen odam*/
	GPIO_writePin(H_BRIDGE_INPUT1_PORT,H_BRIDGE_INPUT1_PIN,GPIO_HIGH_PIN);
	GPIO_writePin(H_BRIDGE_INPUT2_PORT,H_BRIDGE_INPUT2_PIN,GPIO_LOW_PIN);
}


static void MOTOR_SET_SPEED(u8 speed)
{
	PWM_enu_SetDutyCycle(DCMOTOR_SELECT_TIMER,DCMOTOR_SELECT_CHANNEL1,speed);
	if (speed > FALSE)
	{
		PWM_enu_SetDutyCycle(DCMOTOR_SELECT_TIMER2,DCMOTOR_SELECT_CHANNEL1,speed-5);
	}
	else
	{
		PWM_enu_SetDutyCycle(DCMOTOR_SELECT_TIMER2,DCMOTOR_SELECT_CHANNEL1,speed);
	}
	
}