
#include "std_types.h"
#include "common_macros.h"
#include "RCC_interface.h"
#include "DIO_interface.h"
#include "PWM_interface.h"
#include "motor.h"


DcMotor_State state;
/*
initialize DCmotor by passing channel and timer IDs to the PWM init
*/
void DCmotor_Init(void)
{
	MRCC_voidPerClock_State(APB2,IOPA_PERIPHERAL,PClock_enable);
	MRCC_voidPerClock_State(APB2,IOPB_PERIPHERAL,PClock_enable);

	MGPIO_voidSetPinDirection(H_BRIDGE_INPUT1_PORT,H_BRIDGE_INPUT1_PIN,OUTPUT_SPEED_10MHZ_PP);
	MGPIO_voidSetPinDirection(H_BRIDGE_INPUT1_PORT,H_BRIDGE_INPUT2_PIN,OUTPUT_SPEED_10MHZ_PP);
	MGPIO_voidSetPinDirection(H_BRIDGE_INPUT2_PORT,H_BRIDGE_INPUT3_PIN,OUTPUT_SPEED_10MHZ_PP);
	MGPIO_voidSetPinDirection(H_BRIDGE_INPUT2_PORT,H_BRIDGE_INPUT4_PIN,OUTPUT_SPEED_10MHZ_PP);

	MGPIO_voidSetPinValue(H_BRIDGE_INPUT1_PORT,H_BRIDGE_INPUT1_PIN,GPIO_LOW);
	MGPIO_voidSetPinValue(H_BRIDGE_INPUT1_PORT,H_BRIDGE_INPUT2_PIN,GPIO_LOW);
	MGPIO_voidSetPinValue(H_BRIDGE_INPUT2_PORT,H_BRIDGE_INPUT3_PIN,GPIO_LOW);
	MGPIO_voidSetPinValue(H_BRIDGE_INPUT2_PORT,H_BRIDGE_INPUT4_PIN,GPIO_LOW);

	MPWM_voidInit(DCMOTOR_SELECT_TIMER,DCMOTOR_SELECT_CHANNEL,DCMOTOR_MAX_SPEED);
}

void MOTOR_setMotor(u8 a_direction, u8 a_speed)
{
	switch (a_direction)
	{
	case 'F':
		MGPIO_voidSetPinValue(H_BRIDGE_INPUT1_PORT,H_BRIDGE_INPUT2_PIN,GPIO_LOW);
		MGPIO_voidSetPinValue(H_BRIDGE_INPUT2_PORT,H_BRIDGE_INPUT4_PIN,GPIO_LOW);
		MGPIO_voidSetPinValue(H_BRIDGE_INPUT1_PORT,H_BRIDGE_INPUT1_PIN,GPIO_HIGH);
		MGPIO_voidSetPinValue(H_BRIDGE_INPUT2_PORT,H_BRIDGE_INPUT3_PIN,GPIO_HIGH);
		MPWM_SETValuesOfPWM(DCMOTOR_SELECT_TIMER,DCMOTOR_SELECT_CHANNEL,(a_speed * 500));
		break;
	
	case 'B':
		MGPIO_voidSetPinValue(H_BRIDGE_INPUT1_PORT,H_BRIDGE_INPUT1_PIN,GPIO_LOW);
		MGPIO_voidSetPinValue(H_BRIDGE_INPUT2_PORT,H_BRIDGE_INPUT3_PIN,GPIO_LOW);
		MGPIO_voidSetPinValue(H_BRIDGE_INPUT1_PORT,H_BRIDGE_INPUT2_PIN,GPIO_HIGH);
		MGPIO_voidSetPinValue(H_BRIDGE_INPUT2_PORT,H_BRIDGE_INPUT4_PIN,GPIO_HIGH);
		MPWM_SETValuesOfPWM(DCMOTOR_SELECT_TIMER,DCMOTOR_SELECT_CHANNEL,(a_speed * 500));
		break;
	
	case 'R':
		MGPIO_voidSetPinValue(H_BRIDGE_INPUT1_PORT,H_BRIDGE_INPUT1_PIN,GPIO_LOW);
		MGPIO_voidSetPinValue(H_BRIDGE_INPUT2_PORT,H_BRIDGE_INPUT4_PIN,GPIO_LOW);
		MGPIO_voidSetPinValue(H_BRIDGE_INPUT1_PORT,H_BRIDGE_INPUT2_PIN,GPIO_HIGH);
		MGPIO_voidSetPinValue(H_BRIDGE_INPUT2_PORT,H_BRIDGE_INPUT3_PIN,GPIO_HIGH);
		MPWM_SETValuesOfPWM(DCMOTOR_SELECT_TIMER,DCMOTOR_SELECT_CHANNEL,20000);
		break;
	
	case 'L':
		MGPIO_voidSetPinValue(H_BRIDGE_INPUT1_PORT,H_BRIDGE_INPUT2_PIN,GPIO_LOW);
		MGPIO_voidSetPinValue(H_BRIDGE_INPUT2_PORT,H_BRIDGE_INPUT3_PIN,GPIO_LOW);
		MGPIO_voidSetPinValue(H_BRIDGE_INPUT1_PORT,H_BRIDGE_INPUT1_PIN,GPIO_HIGH);
		MGPIO_voidSetPinValue(H_BRIDGE_INPUT2_PORT,H_BRIDGE_INPUT4_PIN,GPIO_HIGH);
		MPWM_SETValuesOfPWM(DCMOTOR_SELECT_TIMER,DCMOTOR_SELECT_CHANNEL,20000);
		break;
	
	case 'S':
		MGPIO_voidSetPinValue(H_BRIDGE_INPUT1_PORT,H_BRIDGE_INPUT1_PIN,GPIO_LOW);
		MGPIO_voidSetPinValue(H_BRIDGE_INPUT2_PORT,H_BRIDGE_INPUT4_PIN,GPIO_LOW);
		MGPIO_voidSetPinValue(H_BRIDGE_INPUT1_PORT,H_BRIDGE_INPUT2_PIN,GPIO_LOW);
		MGPIO_voidSetPinValue(H_BRIDGE_INPUT2_PORT,H_BRIDGE_INPUT3_PIN,GPIO_LOW);
		MPWM_SETValuesOfPWM(DCMOTOR_SELECT_TIMER,DCMOTOR_SELECT_CHANNEL,DCMOTOR_STOP);
		break;
	
	default:
		/* Do Nothing. */
		break;
	}
}

// void DCmotor_frontMove(u8 dutyCycle)
// {
// 	/*ganb shmal odam*/
// 	MGPIO_voidSetPinValue(H_BRIDGE_INPUT2_PORT,H_BRIDGE_INPUT2_PIN,GPIO_HIGH);
// 	MGPIO_voidSetPinValue(H_BRIDGE_INPUT2_PORT,H_BRIDGE_INPUT4_PIN,GPIO_HIGH);

// 	/*ganb ymen odam*/
// 	MGPIO_voidSetPinValue(H_BRIDGE_INPUT1_PORT,H_BRIDGE_INPUT1_PIN,GPIO_LOW);
// 	MGPIO_voidSetPinValue(H_BRIDGE_INPUT1_PORT,H_BRIDGE_INPUT3_PIN,GPIO_LOW);

// 	MPWM_SETValuesOfPWM(DCMOTOR_SELECT_TIMER,DCMOTOR_SELECT_CHANNEL,(dutyCycle * 10));
// }

// void DCmotor_backMove(u8 dutyCycle)
// {
// 	MGPIO_voidSetPinValue(H_BRIDGE_INPUT1_PORT,H_BRIDGE_INPUT3_PIN,GPIO_HIGH);
// 	MGPIO_voidSetPinValue(H_BRIDGE_INPUT1_PORT,H_BRIDGE_INPUT1_PIN,GPIO_HIGH);

// 	/*ganb ymen wra*/
// 	MGPIO_voidSetPinValue(H_BRIDGE_INPUT2_PORT,H_BRIDGE_INPUT2_PIN,GPIO_LOW);
// 	MGPIO_voidSetPinValue(H_BRIDGE_INPUT2_PORT,H_BRIDGE_INPUT4_PIN,GPIO_LOW);

// 	MPWM_SETValuesOfPWM(DCMOTOR_SELECT_TIMER,DCMOTOR_SELECT_CHANNEL,(dutyCycle * 10));
// }

// // input1 right motors , input2 left motors
// void DCmotor_rightMove(u8 dutyCycle)
// {
// 	MGPIO_voidSetPinValue(H_BRIDGE_INPUT2_PORT,H_BRIDGE_INPUT4_PIN,GPIO_LOW);
// 	MGPIO_voidSetPinValue(H_BRIDGE_INPUT1_PORT,H_BRIDGE_INPUT1_PIN,GPIO_LOW);
	
// 	MGPIO_voidSetPinValue(H_BRIDGE_INPUT2_PORT,H_BRIDGE_INPUT2_PIN,GPIO_HIGH);
// 	MGPIO_voidSetPinValue(H_BRIDGE_INPUT1_PORT,H_BRIDGE_INPUT3_PIN,GPIO_HIGH);

// 	MPWM_SETValuesOfPWM(DCMOTOR_SELECT_TIMER,DCMOTOR_SELECT_CHANNEL,(dutyCycle * 10));
// }

// void DCmotor_leftMove(u8 dutyCycle)
// {
// 	MGPIO_voidSetPinValue(H_BRIDGE_INPUT2_PORT,H_BRIDGE_INPUT2_PIN,GPIO_LOW);
// 	MGPIO_voidSetPinValue(H_BRIDGE_INPUT1_PORT,H_BRIDGE_INPUT3_PIN,GPIO_LOW);
	
// 	MGPIO_voidSetPinValue(H_BRIDGE_INPUT2_PORT,H_BRIDGE_INPUT4_PIN,GPIO_HIGH);
// 	MGPIO_voidSetPinValue(H_BRIDGE_INPUT1_PORT,H_BRIDGE_INPUT1_PIN,GPIO_HIGH);

// 	MPWM_SETValuesOfPWM(DCMOTOR_SELECT_TIMER,DCMOTOR_SELECT_CHANNEL,(dutyCycle * 10));
// }
// /*
// stop the DCmotor by passing dutycycle = 0
// */
// void DCmotor_stop(void)
// {
// 	MGPIO_voidSetPinValue(H_BRIDGE_INPUT1_PORT,H_BRIDGE_INPUT1_PIN,GPIO_LOW);
// 	MGPIO_voidSetPinValue(H_BRIDGE_INPUT2_PORT,H_BRIDGE_INPUT4_PIN,GPIO_LOW);
// 	MGPIO_voidSetPinValue(H_BRIDGE_INPUT1_PORT,H_BRIDGE_INPUT2_PIN,GPIO_LOW);
// 	MGPIO_voidSetPinValue(H_BRIDGE_INPUT2_PORT,H_BRIDGE_INPUT3_PIN,GPIO_LOW);
	
// 	MPWM_SETValuesOfPWM(DCMOTOR_SELECT_TIMER,DCMOTOR_SELECT_CHANNEL,DCMOTOR_STOP);
// }